receivers:
  otlp:
    protocols:
      grpc:

exporters:

  logging:
    verbosity: detailed

  prometheusremotewrite:
    endpoint: "http://prometheus:9090/api/v1/write"

  prometheus:
    endpoint: 0.0.0.0:8889
    enable_open_metrics: true
    namespace: default

  otlp/tempo:
    endpoint: "http://tempo:4317"
    tls:
      insecure: true

  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"

service:
  pipelines:
    metrics:
      receivers: [ otlp ]
      exporters: [ prometheusremotewrite ]
    traces:
      receivers: [ otlp ]
      exporters: [ otlp/tempo ]
    logs:
      receivers: [ otlp ]
      exporters: [ loki ]
