receivers:
  otlp:
    protocols:
      grpc:

exporters:

  logging:
    verbosity: detailed

  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: default

  otlp/tempo:
    endpoint: "http://tempo:4317"
    tls:
      insecure: true

  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"

service:
  pipelines:
    metrics:
      receivers: [ otlp ]
      exporters: [ prometheus ]
    traces:
      receivers: [ otlp ]
      exporters: [ otlp/tempo ]
    logs:
      receivers: [ otlp ]
      exporters: [ loki ]
